### 로그인 2 : LoginGuard
POST http://localhost:3000/auth/login2
content-type: application/json

{
    "email": "test1@gmail.com",
    "password": "123"
}

### Guard 테스트
GET http://localhost:3000/auth/test-guard